In [2]:
import numpy as np
#convert list to array
#equal arrays are conditions
dist=[10,560,456,53,56]
time=[50,60,30,50,56]
dist1=np.array(dist)
time1=np.array(time)

In [2]:
type(dist1)

numpy.ndarray

In [3]:
speed=dist1/time1

In [4]:
speed

array([ 0.2       ,  9.33333333, 15.2       ,  1.06      ,  1.        ])

In [5]:
import numpy as np
A= np.array([1,2,2.5,"cetpa"])

In [6]:
type(A)

numpy.ndarray

In [7]:
B=np.array([[1,2,3],[4,5,6]])

In [8]:
B.ndim

2

In [9]:
B.shape

(2, 3)

In [10]:
B.size

6

In [11]:
A.ndim

1

In [12]:
A.shape

(4,)

In [13]:
A.size

4

In [14]:
A.dtype#unicode

dtype('<U32')

In [16]:
list2=[[1,2,3,4],[3,4,5,6],[5,6,7,8]]
arr2=np.array(list2,dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [17]:
arr2>4

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [18]:
arr2[arr2>4]

array([5., 6., 5., 6., 7., 8.])

In [30]:
#two dimensional array Slicing
arr2[1,2]# row and coloumn 
arr2[:,1]# coloumn
arr2[:,1:3]#specific part of an nd array


array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [35]:
#numpy random module
print(np.random.rand(2,2))#2,2 is row and coloumn

[[0.83542997 0.31142593]
 [0.28928486 0.61018485]]


In [41]:
print(np.random.randn(2,2))# normal disturbution mean =0  variance =1
print(np.random.randint(0,10,size=[2,2]))#random integers till [0,10)
print(np.arange(10))

[[-0.33800039 -0.90197865]
 [ 1.38248794 -1.16622558]]
[[6 2]
 [5 2]]
[0 1 2 3 4 5 6 7 8 9]


In [48]:
incomes=np.random.normal(27000,15000,10000)#(average, standard deviation,Data points)
print(incomes)
type(incomes)
print(incomes.ndim)


[28854.90630121 -1189.63380279 23649.93060236 ... 18228.46742946
 39783.31833359 17335.70714094]
1


In [43]:
np.mean(incomes)# finding mean in dataset

27064.391040504717

In [45]:
np.median(incomes)# finding median in dataset

26954.017403689693

In [50]:
a=[[1,2],
   [3,4]]
np.mean(a,axis=1)#row's mean is obtained

array([1.5, 3.5])

In [51]:
np.mean(a,axis=0)# coloumn mean is obtained

array([2., 3.])

In [52]:
ages=np.random.randint(18,high=90,size=500)

In [53]:
print(ages)

[71 76 41 47 28 53 69 34 20 37 30 80 50 77 52 21 18 70 53 18 83 82 76 55
 33 34 64 73 76 28 44 35 67 42 30 75 28 29 37 61 86 39 80 36 51 69 61 20
 38 35 29 29 62 37 71 82 39 43 27 63 46 87 62 59 48 21 27 19 25 65 59 73
 61 34 62 42 59 53 84 56 72 81 45 49 40 29 68 62 56 38 72 64 35 63 66 53
 59 20 30 37 68 52 88 70 27 73 49 79 41 60 19 20 48 42 21 32 48 29 87 36
 74 69 86 76 46 83 24 73 38 69 68 81 65 18 30 28 61 47 79 78 25 70 55 20
 51 71 54 50 64 82 38 65 40 24 25 79 38 50 67 73 65 18 30 36 43 63 28 21
 56 80 61 69 81 49 64 24 73 69 59 75 67 32 35 18 42 41 62 19 43 80 89 66
 33 57 40 81 50 83 64 23 89 21 71 21 89 44 72 56 59 79 40 36 34 73 35 58
 84 72 37 70 25 75 42 83 34 89 48 82 34 51 87 21 68 53 43 40 55 84 40 21
 57 55 60 27 53 65 29 19 41 88 43 84 51 75 53 69 77 88 79 62 56 33 55 76
 62 82 62 82 55 27 32 80 65 44 21 54 65 56 79 21 66 39 20 33 58 50 29 89
 67 76 26 81 32 40 72 68 71 74 78 48 28 23 63 86 67 67 76 19 73 54 24 22
 40 44 54 53 67 37 68 65 19 39 55 30 75 82 77 50 35

In [57]:
# for calculation of mode 
from scipy import stats
stats.mode(ages)

ModeResult(mode=array([21]), count=array([15]))

In [59]:
incomes =np.append(incomes,[100000000])
print(np.median(incomes))
print(np.mean(incomes))

26658.239887124357
46626.22374676731


In [60]:
# if we have outliers in  dataset we don't replace it with mean rather we choose to replace with median
# box and desciption bar chart is used to find outliers

In [7]:
a= np.zeros(10)
print(a)
k=np.ones(10)
z=5*k
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [8]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [10]:
# create a 3*3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
print(np.random.randn(1))

[-0.0861249]


In [22]:
# output 10*10 matrix
(np.arange(101))/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [23]:
#slicing and reshaping
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
mat[3,4]

20

In [28]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [29]:
mat[4]

array([21, 22, 23, 24, 25])

In [33]:
mat[3:5]
# or 
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
# standard deviation,variance,mean, mean for rows and coloumns
np.std(mat)



7.211102550927978

np.var(mat)

In [35]:
np.var(mat)

52.0

In [36]:
np.mean(mat,axis=1)#row

array([ 3.,  8., 13., 18., 23.])

In [37]:
np.mean(mat,axis=0)#column

array([11., 12., 13., 14., 15.])

In [38]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])